name: climate_debunk
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - pytorch
  - transformers
  - nlpaug
  - pytest
  - pytest-mock
  - pyyaml
  - matplotlib
  - jupyter
  - ipykernel
  - nb_conda_kernels
  - seaborn
  - optuna
  - onnx
  - onnxruntime