# Data settings
data_path: "data/train/raw/train.parquet"   # Path to the input dataset
output_dir: "data/train/augmented"          # Directory to save augmented data
n_splits: 5                           # Number of K-Fold splits
random_seed: 42                       # Ensures reproducibility

# Augmentation settings
augmenter_model: "bert-base-uncased"  # NLP model for augmentation
augment_action: "substitute"          # Augmentation type (substitute, insert, delete)
device: "cuda"                        # "cuda" or "cpu" (forces device usage)

save_intermediate_files: False        # Save intermediate files (True/False)

