
# Training Data   - either augmented data or raw data from HF
trainpath : "data/train/aug_balanced_train.csv" # training data 
train_label_col: "numeric_label"

# Validation data for evaluation during training
valpath : "data/valid/test-00000-of-00001.parquet" # validation data
val_label_col: "label"

# Test data for inference
testpath: "path/to/test/data"  # unseen data
test_label_col: "label"
trained_model_path: "models/climatedebunkwithbert.pth" # can be changed to another path in the repo  

# Tokenizer
tokenizer_model : "distilbert-base-uncased"
max_length: 365

# Model
model_name: "distilbert-base-uncased"
total_layers: 6
num_labels: 8

# Hyperparameters
learning_rate : 8.509924985836568e-05 
num_trainable_layers : 4 
dropout_rate : 0.19553005296446951 
batch_size : 16 
epochs : 5 
step_size : 4 
gamma : 0.8523421613311146 

# Output
output_dir : "output"
trained_model_path : "models/climatedebunkwithbert.pth"