# Data
train : "/kaggle/input/balancedfull/" # 5 csv files created with scripts/augment_train.py
test : "/kaggle/input/test-parquet/test-00000-of-00001.parquet" # validation set provided by HF


device : "cuda"

# hyperparams to optimize
hyperparameters:
  learning_rate:
    type: float
    range: [1e-5, 1e-3]
    log: true
  num_trainable_layers:
    type: int
    range: [1, 6]
  dropout_rate:
    type: float
    range: [0.1, 0.5]
  batch_size:
    type: categorical
    values: [16, 32, 64]
  epochs:
    type: int
    range: [2, 5]
  step_size:
    type: int
    range: [1, 10]
  gamma:
    type: float
    range: [0.1, 0.9]
